Fix ReaLearn linking error maybe caused by cc crate update
Calling `cpp_set_stdlib(None)` causes linker to not automatically link,
which breaks Linux build.

ReaLearn error message:

    undefined reference to symbol '_ZdlPvm@@CXXABI_1.3.9'
          //usr/lib/x86_64-linux-gnu/libstdc++.so.6: error adding symbols: DSO missing from command line

see https://github.com/helgoboss/realearn/runs/1468749043?check_suite_focus=true#step:6:503